platform :ios, "13.0"
use_frameworks! :linkage => :dynamic

def pod_Common
  pod "JSMediaBrowser", :path => "../", :subspecs => [
    "Business", 
    "MediaPhotoForSDWebImage", 
    "MediaPhotoForPHLivePhoto"
  ]
  pod "QMUIKit"
  pod "SnapKit"
  pod "Then"
  pod 'SwiftLint', :configurations => ['Debug']
  pod "LookinServer", :subspecs => ['Swift'], :configurations => ["Debug"]
end

target "JSMediaBrowserExample" do
  pod_Common
end

target "JSMediaBrowserExampleMacOS" do
  pod_Common
end

def set_iphoneos_deployment_target(target)
  target.build_configurations.each do |config|
    config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = "13.0"
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    set_iphoneos_deployment_target(target)
  end
end